declare namespace App {
namespace Enum {
export type AchievementType = 'level' | 'monster' | 'weapon' | 'armor';
export type ArmorType = 'HEAD' | 'BODY' | 'LEG';
export type DayType = 'MONSTER' | 'DOWNTIME';
export type DeviationWeapon = 'NONE' | 'LOW' | 'AVERAGE' | 'HIGH';
export type InvitationStatus = 'pending' | 'accepted' | 'revoked' | 'expired';
export type ItemType = 'COMMON' | 'OTHER' | 'MONSTER_PART';
export type MonsterCategory = 'FANGED_WYVERN' | 'PISCINE_WYVERN' | 'BIRD_WYVERN' | 'FLYING_WYVERN' | 'BRUTE_WYVERN' | 'ELDER_DRAGON';
export type MonsterDifficulty = 'EASY' | 'NORMAL' | 'HARD' | 'ARENA_EASY' | 'ARENA_NORMAL' | 'ARENA_HARD';
export type MonsterExpansion = 'ANCIENT_FOREST' | 'WILDSPIRE_WASTE' | 'KULU_YA_KU_EXPANSION' | 'PICKING_BONES' | 'TEOSTRA_EXPANSION' | 'NERGIGANTE_EXPANSION' | 'KUSHALA_EXPANSION' | 'KIRIN_EXPANSION';
}
namespace Models {
export type Achievement = {
id: number,
slug: string,
name: string,
is_secret: boolean,
description: string | null,
type: string | null,
type_count: number | null,
has_progress: boolean,
color: string | null,
image: string | null,
created_at: string | null,
updated_at: string | null,
users?: Array<App.Models.User>,
users_count?: number,
};
export type Armor = {
id: number,
type: string,
name: string,
is_default: boolean,
branch_id: number | null,
expansion: string | null,
branch: string | null,
rarity: number,
defense: number,
defense_fire: number,
defense_water: number,
defense_thunder: number,
defense_ice: number,
defense_dragon: number,
created_at: string | null,
updated_at: string | null,
type_value?: string,
expansion_value?: string | null,
skills?: Array<App.Models.ArmorSkill>,
skills_count?: number,
items?: Array<App.Models.Item>,
items_count?: number,
};
export type ArmorSkill = {
id: number,
name: string,
description: string,
bonus_set: boolean,
bonus_set_armor: unknown[] | null,
created_at: string | null,
updated_at: string | null,
};
export type Campaign = {
id: number,
team_id: number,
name: string,
description: string | null,
max_days: number,
max_days_automatic: boolean,
health_potions: number,
expansions: Array<App.Enum.MonsterExpansion> | null,
created_at: string | null,
updated_at: string | null,
description_parsed?: string,
description_parsed_html?: string,
team?: App.Models.Team,
team_count?: number,
hunters?: Array<App.Models.Hunter>,
hunters_count?: number,
days?: Array<App.Models.Day>,
days_count?: number,
campaign_invitations?: Array<App.Models.CampaignInvitation>,
campaign_invitations_count?: number,
users?: Array<App.Models.User>,
users_count?: number,
};
export type CampaignInvitation = {
id: number,
campaign_id: number,
email: string,
role_id: number,
created_at: string | null,
updated_at: string | null,
campaign?: App.Models.Campaign,
campaign_count?: number,
role?: App.Models.Role,
role_count?: number,
};
export type Craft = {
id: number,
user_id: number,
craftable_type: string,
craftable_id: number,
created_at: string | null,
updated_at: string | null,
user?: App.Models.User,
user_count?: number,
};
export type Day = {
id: number,
campaign_id: number,
monster_id: number | null,
downtime_activity_id: number | null,
number: number,
difficulty: string | null,
hunted: boolean,
all_hunters_same_activity: boolean,
created_at: string | null,
updated_at: string | null,
campaign?: App.Models.Campaign,
campaign_count?: number,
monster?: App.Models.Monster,
monster_count?: number,
downtime_activity?: App.Models.DowntimeActivity,
downtime_activity_count?: number,
hunters?: Array<App.Models.Hunter>,
hunters_count?: number,
};
export type DowntimeActivity = {
id: number,
name: string,
description: string | null,
created_at: string | null,
updated_at: string | null,
};
export type Experience = {
id: number,
user_id: number,
level_id: number,
experience_points: number,
created_at: string | null,
updated_at: string | null,
user?: App.Models.User,
user_count?: number,
level?: App.Models.Level,
level_count?: number,
};
export type Hunter = {
id: number,
campaign_id: number,
weapon_type_id: number | null,
name: string,
created_at: string | null,
updated_at: string | null,
campaign?: App.Models.Campaign,
campaign_count?: number,
weapon_type?: App.Models.WeaponType,
weapon_type_count?: number,
palico?: App.Models.Palico,
palico_count?: number,
days?: Array<App.Models.Day>,
days_count?: number,
items?: Array<App.Models.Item>,
items_count?: number,
weapons?: Array<App.Models.Weapon>,
weapons_count?: number,
equipped_weapons?: Array<App.Models.Weapon>,
equipped_weapons_count?: number,
armors?: Array<App.Models.Armor>,
armors_count?: number,
equipped_armors?: Array<App.Models.Armor>,
equipped_armors_count?: number,
common_items?: Array<App.Models.Item>,
common_items_count?: number,
other_items?: Array<App.Models.Item>,
other_items_count?: number,
monster_items?: Array<App.Models.Item>,
monster_items_count?: number,
};
export type Invitation = {
id: number,
inviter_id: number | null,
email: string | null,
expires_at: string,
accepted_at: string | null,
accepted_by_id: number | null,
revoked_at: string | null,
created_at: string | null,
updated_at: string | null,
status?: App.Enum.InvitationStatus,
inviter?: App.Models.User,
inviter_count?: number,
accepted_by?: App.Models.User,
accepted_by_count?: number,
};
export type Item = {
id: number,
type: string,
name: string,
created_at: string | null,
updated_at: string | null,
icon_path: string | null,
icon_url?: string,
monsters?: Array<App.Models.Monster>,
monsters_count?: number,
weapons?: Array<App.Models.Weapon>,
weapons_count?: number,
armors?: Array<App.Models.Armor>,
armors_count?: number,
};
export type Level = {
id: number,
level: number,
next_level_experience: number | null,
created_at: string | null,
updated_at: string | null,
experiences?: Array<App.Models.Experience>,
experiences_count?: number,
};
export type Membership = {
id: number,
team_id: number,
user_id: number,
role: string | null,
created_at: string | null,
updated_at: string | null,
};
export type Monster = {
id: number,
name: string,
description: string | null,
category: string,
expansion: string,
created_at: string | null,
updated_at: string | null,
resistance_fire: number | null,
resistance_water: number | null,
resistance_thunder: number | null,
resistance_ice: number | null,
resistance_dragon: number | null,
resistance_paralysis: number | null,
resistance_poison: number | null,
resistance_sleep: number | null,
resistance_nitro: number | null,
resistance_stun: number | null,
setup: string | null,
mechanics: Array<{ title: string; description: Array<{ title: string; description: string }> }> | null,
icon_path: string | null,
icon_url?: string,
items?: Array<App.Models.Item>,
items_count?: number,
difficulties?: Array<App.Models.MonsterDifficulty>,
difficulties_count?: number,
rewards?: Array<App.Models.MonsterReward>,
rewards_count?: number,
};
export type MonsterDifficulty = {
id: number,
monster_id: number,
difficulty: string,
stars: number,
health: number,
ability_name: string,
ability_description: string,
created_at: string | null,
updated_at: string | null,
monster?: App.Models.Monster,
monster_count?: number,
parts?: Array<App.Models.MonsterPart>,
parts_count?: number,
};
export type MonsterPart = {
id: number,
monster_difficulty_id: number,
icon: string,
direction: string,
defense: number,
broken: number,
ability_broken: string | null,
position: number,
created_at: string | null,
updated_at: string | null,
difficulty?: App.Models.MonsterDifficulty,
difficulty_count?: number,
};
export type MonsterReward = {
id: number,
monster_id: number,
roll: number,
item_id: number,
extra: string | null,
created_at: string | null,
updated_at: string | null,
monster?: App.Models.Monster,
monster_count?: number,
item?: App.Models.Item,
item_count?: number,
};
export type Palico = {
id: number,
hunter_id: number,
name: string,
created_at: string | null,
updated_at: string | null,
hunter?: App.Models.Hunter,
hunter_count?: number,
};
export type Provider = {
id: number,
user_id: number,
provider: string,
provider_id: string,
name: string | null,
nickname: string | null,
email: string | null,
telephone: string | null,
avatar_path: string | null,
expires_at: string | null,
created_at: string | null,
updated_at: string | null,
user?: App.Models.User,
user_count?: number,
};
export type Song = {
id: number,
song_list_id: number,
song_effect_id: number,
range: number,
notes: unknown[],
position: number,
created_at: string | null,
updated_at: string | null,
list?: App.Models.SongList,
list_count?: number,
effect?: App.Models.SongEffect,
effect_count?: number,
};
export type SongEffect = {
id: number,
name: string,
description: string,
created_at: string | null,
updated_at: string | null,
songs?: Array<App.Models.Song>,
songs_count?: number,
};
export type SongList = {
id: number,
weapon_type_id: number,
name: string,
position: number,
created_at: string | null,
updated_at: string | null,
weapon_type?: App.Models.WeaponType,
weapon_type_count?: number,
songs?: Array<App.Models.Song>,
songs_count?: number,
weapons?: Array<App.Models.Weapon>,
weapons_count?: number,
};
export type Team = {
id: number,
user_id: number,
name: string,
personal_team: boolean,
created_at: string | null,
updated_at: string | null,
campaigns?: Array<App.Models.Campaign>,
campaigns_count?: number,
};
export type TeamInvitation = {
id: number,
team_id: number,
email: string,
role: string | null,
created_at: string | null,
updated_at: string | null,
team?: App.Models.Team,
team_count?: number,
};
export type User = {
id: number,
name: string,
email: string,
email_verified_at: string | null,
two_factor_confirmed_at: string | null,
current_team_id: number | null,
current_connected_account_id: number | null,
profile_photo_path: string | null,
created_at: string | null,
updated_at: string | null,
profile_photo_url?: string,
campaigns?: Array<App.Models.Campaign>,
campaigns_count?: number,
sent_invitations?: Array<App.Models.Invitation>,
sent_invitations_count?: number,
providers?: Array<App.Models.Provider>,
providers_count?: number,
hunters?: Array<App.Models.Hunter>,
hunters_count?: number,
crafts?: Array<App.Models.Craft>,
crafts_count?: number,
all_achievements?: Array<App.Models.Achievement>,
all_achievements_count?: number,
achievements?: Array<App.Models.Achievement>,
achievements_count?: number,
achievements_with_progress?: Array<App.Models.Achievement>,
achievements_with_progress_count?: number,
experience?: App.Models.Experience,
experience_count?: number,
roles?: Array<App.Models.Role>,
roles_count?: number,
permissions?: Array<App.Models.Permission>,
permissions_count?: number,
};
export type Weapon = {
id: number,
type_id: number,
parent_id: number | null,
name: string,
is_default: boolean,
rarity: number,
defense: number,
count_attack_1: number,
count_attack_2: number,
count_attack_3: number,
count_attack_4: number,
count_attack_5: number,
has_elemental_attacks: boolean,
element: string | null,
status_attacks: unknown[] | null,
deviation: string | null,
song_list_id: number | null,
created_at: string | null,
updated_at: string | null,
deviation_key?: string | null,
type?: App.Models.WeaponType,
type_count?: number,
song_list?: App.Models.SongList,
song_list_count?: number,
parent?: App.Models.Weapon,
parent_count?: number,
children?: Array<App.Models.Weapon>,
children_count?: number,
recipes?: Array<App.Models.WeaponRecipe>,
recipes_count?: number,
items?: Array<App.Models.Item>,
items_count?: number,
attacks_to_add?: Array<App.Models.WeaponAttack>,
attacks_to_add_count?: number,
attacks_to_remove?: Array<App.Models.WeaponAttack>,
attacks_to_remove_count?: number,
};
export type WeaponAttack = {
id: number,
name: string,
description: string | null,
created_at: string | null,
updated_at: string | null,
};
export type WeaponRecipe = {
id: number,
weapon_id: number,
branch: string | null,
branch_id: number | null,
expansion: string | null,
position: number,
created_at: string | null,
updated_at: string | null,
expansion_label?: string | null,
weapon?: App.Models.Weapon,
weapon_count?: number,
monster?: App.Models.Monster,
monster_count?: number,
items?: Array<App.Models.Item>,
items_count?: number,
};
export type WeaponType = {
id: number,
name: string,
description: string | null,
image_path: string | null,
default_armor: unknown[] | null,
created_at: string | null,
updated_at: string | null,
image_url?: string,
weapons?: Array<App.Models.Weapon>,
weapons_count?: number,
song_lists?: Array<App.Models.SongList>,
song_lists_count?: number,
};
namespace Pivot {
export type ArmorSkill = {
id: number,
armor_id: number,
armor_skill_id: number,
created_at: string | null,
updated_at: string | null,
};
export type CampaignMembership = {
id: number,
campaign_id: number,
user_id: number,
role_id: number,
hunter_id: number | null,
created_at: string | null,
updated_at: string | null,
role?: App.Models.Role,
role_count?: number,
hunter?: App.Models.Hunter,
hunter_count?: number,
};
export type CountItemArmor = {
id: number,
armor_id: number,
item_id: number,
number: number,
created_at: string | null,
updated_at: string | null,
};
export type CountItemHunter = {
id: number,
item_id: number,
hunter_id: number,
number: number,
created_at: string | null,
updated_at: string | null,
};
export type CountItemWeapon = {
id: number,
item_id: number,
weapon_id: number,
weapon_recipe_id: number | null,
number: number,
created_at: string | null,
updated_at: string | null,
};
export type CountWeaponAttackAdd = {
id: number,
weapon_id: number,
weapon_attack_id: number,
number: number,
created_at: string | null,
updated_at: string | null,
};
export type CountWeaponAttackRemove = {
id: number,
weapon_id: number,
weapon_attack_id: number,
number: number,
created_at: string | null,
updated_at: string | null,
};
export type DayDowntimeActivityHunter = {
id: number,
day_id: number,
downtime_activity_id: number | null,
hunter_id: number,
created_at: string | null,
updated_at: string | null,
downtime_activity?: App.Models.DowntimeActivity,
downtime_activity_count?: number,
};
export type HunterArmor = {
id: number,
armor_id: number,
hunter_id: number,
equipped: number,
created_at: string | null,
updated_at: string | null,
};
export type HunterWeapon = {
id: number,
hunter_id: number,
weapon_id: number,
equipped: number,
created_at: string | null,
updated_at: string | null,
};
}
}
}
