/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.cache.delete": [
        {
            "name": "key"
        }
    ],
    "debugbar.queries.explain": [],
    "debugbar.clockwork": [
        {
            "name": "id"
        }
    ],
    "debugbar.assets": [],
    "boost.browser-logs": [],
    "dusk.login": [
        {
            "name": "userId"
        },
        {
            "name": "guard"
        }
    ],
    "dusk.logout": [
        {
            "name": "guard"
        }
    ],
    "dusk.user": [
        {
            "name": "guard"
        }
    ],
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.email": [],
    "password.update": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag"
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag"
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id"
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id"
        }
    ],
    "horizon.index": [
        {
            "name": "view"
        }
    ],
    "terms.show": [],
    "policy.show": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "current-user.destroy": [],
    "teams.create": [],
    "teams.store": [],
    "teams.show": [
        {
            "name": "team"
        }
    ],
    "teams.update": [
        {
            "name": "team"
        }
    ],
    "teams.destroy": [
        {
            "name": "team"
        }
    ],
    "current-team.update": [],
    "team-members.store": [
        {
            "name": "team"
        }
    ],
    "team-members.update": [
        {
            "name": "team"
        },
        {
            "name": "user"
        }
    ],
    "team-members.destroy": [
        {
            "name": "team"
        },
        {
            "name": "user"
        }
    ],
    "team-invitations.accept": [
        {
            "name": "invitation"
        }
    ],
    "team-invitations.destroy": [
        {
            "name": "invitation"
        }
    ],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "qa-login": [],
    "welcome": [],
    "language": [
        {
            "name": "language"
        }
    ],
    "dashboard": [],
    "search": [],
    "global-search": [],
    "wiki.index": [],
    "wiki.monster.index": [],
    "wiki.monster.show": [
        {
            "name": "monster",
            "binding": "id"
        }
    ],
    "wiki.monster.card": [
        {
            "name": "monster",
            "binding": "id"
        }
    ],
    "wiki.item.index": [],
    "wiki.item.show": [
        {
            "name": "item",
            "binding": "id"
        }
    ],
    "wiki.armor.index": [],
    "wiki.armor.show": [
        {
            "name": "armor",
            "binding": "id"
        }
    ],
    "wiki.weapon.index": [],
    "wiki.weapon.type": [
        {
            "name": "weaponType",
            "binding": "id"
        }
    ],
    "wiki.weapon.show": [
        {
            "name": "weapon",
            "binding": "id"
        }
    ],
    "campaigns.index": [],
    "campaigns.create": [],
    "campaigns.store": [],
    "campaigns.show": [
        {
            "name": "campaign",
            "binding": "id"
        }
    ],
    "campaigns.edit": [
        {
            "name": "campaign",
            "binding": "id"
        }
    ],
    "campaigns.update": [
        {
            "name": "campaign",
            "binding": "id"
        }
    ],
    "campaigns.destroy": [
        {
            "name": "campaign",
            "binding": "id"
        }
    ],
    "campaigns.update-potions": [
        {
            "name": "campaign",
            "binding": "id"
        }
    ],
    "campaigns.add-day": [
        {
            "name": "campaign",
            "binding": "id"
        }
    ],
    "campaigns.update-day": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "day",
            "binding": "id"
        }
    ],
    "campaign-members.store": [
        {
            "name": "campaign",
            "binding": "id"
        }
    ],
    "campaign-members.update": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "user"
        }
    ],
    "campaign-members.destroy": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "user",
            "binding": "id"
        }
    ],
    "campaign-invitations.destroy": [
        {
            "name": "invitation",
            "binding": "id"
        }
    ],
    "campaigns.hunters.index": [
        {
            "name": "campaign",
            "binding": null
        }
    ],
    "campaigns.hunters.create": [
        {
            "name": "campaign",
            "binding": null
        }
    ],
    "campaigns.hunters.store": [
        {
            "name": "campaign",
            "binding": null
        }
    ],
    "campaigns.hunters.edit": [
        {
            "name": "campaign",
            "binding": null
        },
        {
            "name": "hunter",
            "binding": null
        }
    ],
    "campaigns.hunters.update": [
        {
            "name": "campaign",
            "binding": null
        },
        {
            "name": "hunter",
            "binding": null
        }
    ],
    "campaigns.hunters.destroy": [
        {
            "name": "campaign",
            "binding": null
        },
        {
            "name": "hunter",
            "binding": null
        }
    ],
    "campaigns.hunters.weapon-type.index": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "weaponType",
            "binding": "id"
        }
    ],
    "campaigns.hunters.weapons.craft": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "weaponType",
            "binding": "id"
        },
        {
            "name": "weapon",
            "binding": "id"
        }
    ],
    "campaigns.hunters.weapons.equip": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "weaponType",
            "binding": "id"
        },
        {
            "name": "weapon",
            "binding": "id"
        }
    ],
    "campaigns.hunters.weapon-type.hunt": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "weaponType",
            "binding": "id"
        }
    ],
    "campaigns.hunters.armors.craft": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "armor",
            "binding": "id"
        }
    ],
    "campaigns.hunters.armors.equip": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "armor",
            "binding": "id"
        }
    ],
    "campaigns.hunters.show": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "tab"
        },
        {
            "name": "weaponType",
            "binding": "id"
        }
    ],
    "campaigns.hunters.items.store-many": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        }
    ],
    "campaigns.hunters.items.update-count": [
        {
            "name": "campaign",
            "binding": "id"
        },
        {
            "name": "hunter",
            "binding": "id"
        },
        {
            "name": "item",
            "binding": "id"
        }
    ],
    "profile.level": [],
    "auth.social.redirect": [
        {
            "name": "provider"
        }
    ],
    "auth.social.callback": [
        {
            "name": "provider"
        }
    ],
    "invitations.store": [],
    "invitations.resend": [
        {
            "name": "invitation",
            "binding": "id"
        }
    ],
    "invitations.destroy": [
        {
            "name": "invitation",
            "binding": "id"
        }
    ],
    "profile.social.redirect": [
        {
            "name": "provider"
        }
    ],
    "profile.social.unlink": [
        {
            "name": "provider"
        }
    ],
    "campaign-invitations.accept": [
        {
            "name": "invitation",
            "binding": "id"
        }
    ],
    "campaign-invitations.register": [
        {
            "name": "invitation",
            "binding": "id"
        }
    ],
    "invitations.show": [
        {
            "name": "token"
        }
    ],
    "invitations.accept": [
        {
            "name": "token"
        }
    ]
}
}
export {};
