<?php

use App\Enum\ItemType;

return [
    ItemType::COMMON->name => [
        'Carbalite Ore',
        'Machalite Ore',
        'Dragonite Ore',
        'Fucium Ore',
        'Quality Bone',
        'Monster Bone Small',
        'Monster Bone Medium',
        'Monster Bone Large',
        'Monster Keenbone',
        'Monster Hardbone',
        'Ancient Bone',
        'Boulder Bone',
        'Dragonvein Crystal',
        'Wingdrake Hide',
    ],
    ItemType::OTHER->name => [
        'Firecell Stone',
        'Warm Pelt',
        'Fertile Mud',
        'Gajau Scale',
        'Sharp Claw',
        'Piercing Claw',
        'Coral Crystal',
        'Lightcrystal',
        'Novacrystal',
        'Earth Crystal',
        'Elder Dragon Bone',
        'Elder Dragon Blood',
    ],
    ItemType::MONSTER_PART->name => [
        'Great Jagras Hide',
        'Great Jagras Mane',
        'Great Jagras Claw',
        'Great Jagras Scale',

        'Tobi-Kadachi Pelt',
        'Tobi-Kadachi Claw',
        'Tobi-Kadachi Membrane',
        'Tobi-Kadachi Scale',
        'Tobi-Kadachi Electrode',
        'Electro Sac',
        'Thunder Sac',

        'Anjanath Pelt',
        'Anjanath Scale',
        'Anjanath Tail',
        'Anjanath Fang',
        'Anjanath Nosebone',

        'Rathalos Scale',
        'Rathalos Shell',
        'Rathalos Marrow',
        'Rathalos Webbing',
        'Rathalos Plate',
        'Rathalos Wingtalon',
        'Rathalos Tail',
        'Rathalos Wing',
        'Rathalos Carapace',
        'Rathalos Medulla',
        'Flame Sac',
        'Inferno Sac',

        'Azure Rathalos Scale',
        'Azure Rathalos Carapace',
        'Azure Rathalos Marrow',
        'Azure Rathalos Wing',
        'Azure Rathalos Plate',
        'Azure Rathalos Wingtalon',
        'Azure Rathalos Tail',

        'Barroth Ridge',
        'Barroth Tail',
        'Barroth Claw',
        'Barroth Carapace',
        'Barroth Shell',

        'Pukei-Pukei Carapace',
        'Pukei-Pukei Tail',
        'Pukei-Pukei Wing',
        'Pukei-Pukei Scale',
        'Pukei-Pukei Sac',
        'Pukei-Pukei Quill',
        'Poison Sac',
        'Toxic Sac',

        'Jyuratodus Scale',
        'Jyuratodus Carapace',
        'Jyuratodus Fin',
        'Jyuratodus Fang',
        'Torrent Sac',

        'Diablos Ridge',
        'Diablos Fang',
        'Diablos Carapace',
        'Majestic Horn',
        'Blos Medulla',

        'Black Diablos Ridge',
        'Black Diablos Carapace',
        'Black Spiral Horn',

        'Wyvern Gem',
        'Bird Wyvern Gem',

        'Kulu-Ya-Ku Scale',
        'Kulu-Ya-Ku Hide',
        'Kulu-Ya-Ku Plume',
        'Kulu-Ya-Ku Beak',

        'Nergigante Horn',
        'Nergigante Carapace',
        'Nergigante Talon',
        'Nergigante Tail',
        'Nergigante Gem',
        'Nergigante Regrowth Plate',
        'Immortal Dragonscale',

        'Fire Dragon Scale',
        'Teostra Claw',
        'Teostra Mane',
        'Teostra Carapace',
        'Teostra Powder',
        'Teostra Horn',
        'Teostra Tail',
        'Teostra Webbing',
        'Teostra Gem',

        'Daora Dragon Scale',
        'Daora Carapace',
        'Daora Claw',
        'Daora Webbing',
        'Daora Tail',
        'Daora Horn',
        'Daora Gem',
    ],
];
