<?php

return [
    'Great Jagras' => [
        'name' => 'Gran Jagras',
        'category' => \App\Enum\MonsterCategory::FANGED_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::ANCIENT_FOREST,
        'items' => [
            'Great Jagras Hide',
            'Great Jagras Mane',
            'Great Jagras Claw',
            'Great Jagras Scale',
        ],
    ],
    'Tobi-Kadachi' => [
        'category' => \App\Enum\MonsterCategory::FANGED_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::ANCIENT_FOREST,
        'items' => [
            'Tobi-Kadachi Pelt',
            'Tobi-Kadachi Claw',
            'Tobi-Kadachi Membrane',
            'Tobi-Kadachi Scale',
            'Tobi-Kadachi Electrode',
            'Electro Sac',
            'Thunder Sac',
        ],
    ],
    'Anjanath' => [
        'category' => \App\Enum\MonsterCategory::BRUTE_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::ANCIENT_FOREST,
        'items' => [
            'Anjanath Pelt',
            'Anjanath Scale',
            'Anjanath Tail',
            'Anjanath Fang',
            'Anjanath Nosebone',
        ],
    ],
    'Rathalos' => [
        'category' => \App\Enum\MonsterCategory::FLYING_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::ANCIENT_FOREST,
        'items' => [
            'Rathalos Scale',
            'Rathalos Shell',
            'Rathalos Marrow',
            'Rathalos Webbing',
            'Rathalos Plate',
            'Rathalos Wingtalon',
            'Rathalos Tail',
            'Rathalos Wing',
            'Rathalos Carapace',
            'Rathalos Medulla',
            'Flame Sac',
            'Inferno Sac',
        ],
    ],
    'Azure Rathalos' => [
        'name' => 'Rathalos Celeste',
        'category' => \App\Enum\MonsterCategory::FLYING_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::ANCIENT_FOREST,
        'items' => [
            'Azure Rathalos Scale',
            'Azure Rathalos Carapace',
            'Azure Rathalos Marrow',
            'Azure Rathalos Wing',
            'Azure Rathalos Plate',
            'Azure Rathalos Wingtalon',
            'Azure Rathalos Tail',
        ],
    ],

    'Barroth' => [
        'category' => \App\Enum\MonsterCategory::BRUTE_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::WILDSPIRE_WASTE,
        'items' => [
            'Barroth Ridge',
            'Barroth Tail',
            'Barroth Claw',
            'Barroth Carapace',
            'Barroth Shell',
        ],
    ],
    'Pukei-Pukei' => [
        'category' => \App\Enum\MonsterCategory::BIRD_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::WILDSPIRE_WASTE,
        'items' => [
            'Pukei-Pukei Carapace',
            'Pukei-Pukei Tail',
            'Pukei-Pukei Wing',
            'Pukei-Pukei Scale',
            'Pukei-Pukei Sac',
            'Pukei-Pukei Quill',
            'Poison Sac',
            'Toxic Sac',
        ],
    ],
    'Jyuratodus' => [
        'category' => \App\Enum\MonsterCategory::PISCINE_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::WILDSPIRE_WASTE,
        'items' => [
            'Jyuratodus Scale',
            'Jyuratodus Carapace',
            'Jyuratodus Fin',
            'Jyuratodus Fang',
            'Jyuratodus Shell',
            'Jyuratodus Shell',
            'Aqua Sac',
            'Torrent Sac',
        ],
    ],
    'Diablos' => [
        'category' => \App\Enum\MonsterCategory::FLYING_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::WILDSPIRE_WASTE,
        'items' => [
            'Diablos Ridge',
            'Diablos Fang',
            'Diablos Carapace',
            'Diablos Shell',
            'Majestic Horn',
            'Twisted Horn',
            'Blos Medulla',
        ],
    ],
    'Black Diablos' => [
        'name' => 'Diablos Negra',
        'category' => \App\Enum\MonsterCategory::FLYING_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::WILDSPIRE_WASTE,
        'items' => [
            'Black Diablos Ridge',
            'Black Diablos Carapace',
            'Black Spiral Horn',
        ],
    ],

    'Kulu-Ya-Ku' => [
        'category' => \App\Enum\MonsterCategory::BIRD_WYVERN,
        'expansion' => \App\Enum\MonsterExpansion::KULU_YA_KU_EXPANSION,
        'items' => [
            'Kulu-Ya-Ku Scale',
            'Kulu-Ya-Ku Hide',
            'Kulu-Ya-Ku Plume',
            'Kulu-Ya-Ku Beak',
        ],
    ],

    'Teostra' => [
        'category' => \App\Enum\MonsterCategory::ELDER_DRAGON,
        'expansion' => \App\Enum\MonsterExpansion::TEOSTRA_EXPANSION,
        'items' => [
            'Fire Dragon Scale',
            'Teostra Claw',
            'Teostra Mane',
            'Teostra Carapace',
            'Teostra Powder',
            'Teostra Horn',
            'Teostra Tail',
            'Teostra Webbing',
            'Teostra Gem',
        ],
    ],
    'Nergigante' => [
        'category' => \App\Enum\MonsterCategory::ELDER_DRAGON,
        'expansion' => \App\Enum\MonsterExpansion::NERGIGANTE_EXPANSION,
        'items' => [
            'Nergigante Horn',
            'Nergigante Carapace',
            'Nergigante Talon',
            'Nergigante Tail',
            'Nergigante Gem',
            'Nergigante Regrowth Plate',
            'Immortal Dragonscale',
        ],
    ],
    'Kushala Daora' => [
        'category' => \App\Enum\MonsterCategory::ELDER_DRAGON,
        'expansion' => \App\Enum\MonsterExpansion::KUSHALA_EXPANSION,
        'items' => [
            'Daora Dragon Scale',
            'Daora Carapace',
            'Daora Claw',
            'Daora Webbing',
            'Daora Tail',
            'Daora Horn',
            'Daora Gem',
        ],
    ],
];
